// src/lib/registry/ui/tabs/tabs-list.svelte
<script lang="ts">
	import { Tabs as TabsPrimitive } from "bits-ui";
	import { cn } from "$lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: TabsPrimitive.ListProps = $props();
</script>

<TabsPrimitive.List
	bind:ref
	data-slot="tabs-list"
	class={cn(
		"border inline-flex h-12 w-full items-center justify-center rounded-lg p-1.5",
		className
	)}
	{...restProps}
/>

// src/lib/registry/ui/tabs/tabs-list.tsx
"use client";

import * as React from "react";
import * as TabsPrimitive from "@radix-ui/react-tabs";

import { cn } from "@/lib/utils";

const TabsList = React.forwardRef<
  React.ElementRef<typeof TabsPrimitive.List>,
  React.ComponentPropsWithoutRef<typeof TabsPrimitive.List>
>(({ className, ...props }, ref) => (
  <TabsPrimitive.List
    ref={ref}
    data-slot="tabs-list"
    className={cn("border inline-flex h-12 w-full items-center justify-center rounded-lg p-1.5", className)}
    {...props}
  />
));
TabsList.displayName = "TabsList";

export default TabsList;
export { TabsList };
