// src/lib/components/component-preview.svelte
<script lang="ts">
  import type { Component, Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { page } from '$app/state';
  import CodeBlock from '$lib/components/code-block.svelte';
  import { cn } from '$lib/utils';

  const exampleComponents = $derived(
    (page.data.exampleComponents ?? {}) as Record<string, Component>
  );

  let {
    class: className,
    align = 'center',
    component,
    example,
    children,
    name,
    ...restProps
  }: HTMLAttributes<HTMLElement> & {
    align?: 'center' | 'start' | 'end';
    hideCode?: boolean;
    example?: Snippet;
    component?: Component;
    name: string;
  } = $props();

  let previewComponent = $derived(component ?? exampleComponents[name]);
</script>

{#snippet ExampleFallback()}
  {#if previewComponent}
    {@const PreviewComponent = previewComponent}
    <PreviewComponent />
  {:else}
    <p class="text-sm text-muted-foreground">
      Component
      <code class="relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-sm">
        {name}
      </code>
      not found in registry.
    </p>
  {/if}
{/snippet}

<div
  class={cn(
    'no-prose-docs group relative mt-4 mb-12 flex flex-col rounded-lg border overflow-hidden',
    className
  )}
  {...restProps}
>
  <div>
    <div
      data-slot="preview"
      class="preview flex justify-center"
    >
      <div
        data-align={align}
        class="preview flex min-h-112.5 w-full justify-center border-b p-10 data-[align=center]:items-center data-[align=end]:items-end data-[align=start]:items-start"
      >
        {#if example}
          {@render example()}
        {:else}
          {@render ExampleFallback()}
        {/if}
      </div>
    </div>
    <CodeBlock class="border-0 rounded-none" {name} {children} />
  </div>
</div>

// src/components/component-preview.tsx
"use client";

import * as React from "react";
import { CodeBlock } from "@/components/code-block";
import { cn } from "@/lib/utils";

interface ComponentPreviewProps extends React.HTMLAttributes<HTMLDivElement> {
  align?: "center" | "start" | "end";
  name: string;
  children?: React.ReactNode;
}

export function ComponentPreview({
  className,
  align = "center",
  name,
  children,
  ...props
}: ComponentPreviewProps) {
  return (
    <div
      className={cn(
        "no-prose-docs group relative mt-4 mb-12 flex flex-col overflow-hidden rounded-lg border",
        className
      )}
      {...props}
    >
      <div>
        <div data-slot="preview" className="preview flex justify-center">
          <div
            data-align={align}
            className="preview flex min-h-[450px] w-full justify-center border-b p-10 data-[align=center]:items-center data-[align=end]:items-end data-[align=start]:items-start"
          >
            {children ?? (
              <p className="text-sm text-muted-foreground">
                Component{" "}
                <code className="relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-sm">
                  {name}
                </code>{" "}
                not found in registry.
              </p>
            )}
          </div>
        </div>
        <CodeBlock className="rounded-none border-0" name={name} />
      </div>
    </div>
  );
}
