// src/lib/registry/ui/avatar/avatar-group.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "$lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="avatar-group"
	class={cn(
		"cn-avatar-group *:data-[slot=avatar]:ring-background group/avatar-group flex -space-x-2 *:data-[slot=avatar]:ring",
		className
	)}
	{...restProps}
>
	{@render children?.()}
</div>

// src/lib/registry/ui/avatar/avatar-group.tsx
"use client";

import * as React from "react";
import { cn } from "@/lib/utils";

export type AvatarGroupProps = React.ComponentPropsWithoutRef<"div">;

const AvatarGroup = React.forwardRef<HTMLDivElement, AvatarGroupProps>(
  ({ className, children, ...props }, ref) => (
    <div
      ref={ref}
      data-slot="avatar-group"
      className={cn(
        "cn-avatar-group *:data-[slot=avatar]:ring-background group/avatar-group flex -space-x-2 *:data-[slot=avatar]:ring",
        className
      )}
      {...props}
    >
      {children}
    </div>
  )
);

AvatarGroup.displayName = "AvatarGroup";

export default AvatarGroup;
